f1=open("movie.txt","w")
title=input("영화 제목을 입력해주세요:")
fee=input("티켓 비용을 입력해주세요:")
f1.write(title+"\n")
f1.write(fee)
f1.close()

f1=open("movie.txt","r")
title=f1.readline()
fee=f1.readline()
print("영화제목:",title)
print("티켓요금",fee)
f1.close()
