f1=open("movie.txt","r")
title=f1.readline()
fee=f1.readline()
f1.close()
print("관람 가능한 영화와 요금 안내")
print("영화제목:",title)
print("요금:",fee)

name=input("예약자 이름:")
date=input("예약 날짜와 시간:")
num=input("인원:")

total=int(num)*int(fee)
f2=open("reserve.txt","a")
print("지불할 금액:",total)
f2.write("예약자명:"+name+"\n")
f2.write("예약일시:"+date+"\n")
f2.write("에약인원:"+num+"\n")
f2.write("지불금액:"+str(total)+"\n")
f2.close()
